name: 'Pass all associated open PR to draft'
description: 'Pass all associated open PR to draft'
author: 'Andrew Valleteau'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  branch_name:
    description: 'The current branch name'
    required: true
  github_token:
    description: 'The GitHub token (if not provided the environment variable GITHUB_TOKEN will be used instead)'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
